### ISSUE TITLE
jediterm.sh fails to find java files in /kotlin/ folder

### ISSUE THREAD

**Issue by volth** [JetBrains/jediterm#187]
Simple running ```./jediterm.sh``` fails with
```
> Task :JediTerm:run FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: com/jediterm/app/JediTabbedTerminalWidget
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.jediterm.app.JediTerm.createTabbedTerminalWidget(JediTermMain.kt:71)
        at com.jediterm.app.JediTerm.createTabbedTerminalWidget(JediTermMain.kt:65)
        at com.jediterm.terminal.ui.AbstractTerminalFrame.<init>(AbstractTerminalFrame.java:139)
        at com.jediterm.app.JediTerm.<init>(JediTermMain.kt:65)
        at com.jediterm.app.JediTermMain.main(JediTermMain.kt:42)
Caused by: java.lang.ClassNotFoundException: com.jediterm.app.JediTabbedTerminalWidget
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more

```

I managed to fix it by moving .java-files from
[```JediTerm/src/main/kotlin/com/jediterm/app```](https://github.com/JetBrains/jediterm/tree/master/JediTerm/src/main/kotlin/com/jediterm/app) to ```JediTerm/src/main/java/com/jediterm/app```

Not sure if the fix is related to the cause of the issue.
Those files in ```JediTerm/src/main/kotlin/com/jediterm/app``` are there for more than 2 years, and I remember ```./jediterm.sh``` worked a year ago.

**Comment by segrey** [comment]
@volth Yep, that was the issue. Caused by recent update (in Aug 2018) of kotlin gradle plugin. Fixed now by moving java sources to the java source root.
