### ISSUE TITLE
ESC sequences crash the JediTerm

### ISSUE THREAD

**Issue by istoph** [JetBrains/jediterm#193]
The following two move cursor ESC sequences cause the JediTerm to crash. Tested on master https://github.com/JetBrains/jediterm/commit/faa6d1df3cd62acdc59823832ef57203e57d1802

To reproduce, open a bash in JediTerm and insert the command:
```
echo -e '\033[79C\033[K'
```
or 
```
echo -e '\033[9999C\033[K'
```

Java crash dump:
```
./jediterm.sh

> Task :JediTerm:run
0 [main] INFO com.pty4j.util.ExtractedNative  - Extracted pty4j native in 17 ms
21884 [Connector-Local] ERROR com.jediterm.terminal.TerminalStarter  - Caught exception in terminal thread
java.lang.NegativeArraySizeException
        at com.jediterm.terminal.model.CharBuffer.<init>(CharBuffer.java:44)
        at com.jediterm.terminal.model.TerminalLine.clearArea(TerminalLine.java:233)
        at com.jediterm.terminal.model.LinesBuffer.clearArea(LinesBuffer.java:179)
        at com.jediterm.terminal.model.TerminalTextBuffer.eraseCharacters(TerminalTextBuffer.java:424)
        at com.jediterm.terminal.model.JediTerminal.eraseInLine(JediTerminal.java:392)
        at com.jediterm.terminal.emulator.JediEmulator.eraseInLine(JediEmulator.java:738)
        at com.jediterm.terminal.emulator.JediEmulator.processControlSequence(JediEmulator.java:379)
        at com.jediterm.terminal.emulator.JediEmulator.processEscapeSequence(JediEmulator.java:104)
        at com.jediterm.terminal.emulator.JediEmulator.processChar(JediEmulator.java:78)
        at com.jediterm.terminal.DataStreamIteratingEmulator.next(DataStreamIteratingEmulator.java:36)
        at com.jediterm.terminal.TerminalStarter.start(TerminalStarter.java:54)
        at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:362)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by istoph** [comment]
In the current version on master it does not crash.
